version: '3.5'
services:
  php:
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./docker/php_settings.ini:/usr/local/etc/php/conf.d/php_settings.ini:ro
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
      - /app/vendor

  node:
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - /app/node_modules

  mysql:
    image: mysql:8.0.40
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - dev-site

networks:
  dev-site:
    name: dev-site
    driver: bridge
