services:
  php:
    image: ghcr.io/codelits/dev-site:php-latest
    build:
      dockerfile: docker/PHP.production.dockerfile
      context: .
    volumes:
      - ./public:/app/public
    networks:
      - nginx_network

  node:
    image: ghcr.io/codelits/dev-site:node-latest
    build:
      dockerfile: docker/NodeClient.production.dockerfile
      context: .
    volumes:
      - ./public:/app/public
    networks:
      - nginx_network


networks:
  nginx_network:
    external: true
