version: '3'
services:
  mix:
    image: ghcr.io/codelit/dev-site
    platform: linux/x86_64
    build:
      dockerfile: ./docker/mix/Dockerfile
      context: .
    ports:
      - '35729:35729' # Livereload
    volumes:
      - .:/app
  composer:
    depends_on:
      - mix
    image: composer/composer
    tty: true
    working_dir: /app
    command: install
    volumes:
      - .:/app
