version: '3.5'
services:
  dev-site:
    container_name: dev-site
    image: ghcr.io/codelit/dev-site
    restart: always
    tty: true
    build:
      dockerfile: docker/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      # Important data files
      - .env:/app/.env
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
      # Nginx static files shared volumes
      - dev-site:/app

volumes:
  dev-site:
    name: dev-site
