# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel.test:
    build:
      context: ./docker/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
#    depends_on:
#      - mysql
  mix:
    build:
      dockerfile: docker/mix/Dockerfile
    volumes:
      - './public:/app/public'
      - './resources:/app/resources'
      - type: bind
        source: ./package.json
        target: /app/package.json
      - type: bind
        source: ./yarn.lock
        target: /app/yarn.lock
    ports:
      - '35729:35729'
    env_file:
      - .env
#  mysql:
#    image: 'mysql/mysql-server:8.0'
#    ports:
#      - '${FORWARD_DB_PORT:-3306}:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_ROOT_HOST: "%"
#      MYSQL_DATABASE: '${DB_DATABASE}'
#      MYSQL_USER: '${DB_USERNAME}'
#      MYSQL_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    volumes:
#      - 'sail-mysql:/var/lib/mysql'
#      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
#    networks:
#      - sail
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
#      retries: 3
#      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
