version: '3.5'
services:
  dev-site:
    container_name: dev-site
    image: ghcr.io/codelit/dev-site
    restart: always
    tty: true
    depends_on:
      - mysql
    build:
      dockerfile: docker/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      # Important data files
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
      # Nginx static files shared volumes
      - dev-site:/app/public
    networks:
      - internal
      - nginx
  mysql:
    image: mysql:8.3
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal


networks:
  nginx:
    name: nginx
    external: true
  internal:
    internal: true
    driver: bridge

volumes:
  dev-site:
    name: dev-site
