services:
  php:
    container_name: dev_site_php
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./docker/php_settings.ini:/usr/local/etc/php/conf.d/php_settings.ini:ro
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
      - ./bootstrap:/app/bootstrap
      - ./public:/app/public
      - /app/vendor
    networks:
      - dev_site_network

  node:
    container_name: dev_site_node
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./bootstrap:/app/bootstrap
      - ./public:/app/public
      - /app/node_modules
    networks:
      - dev_site_network

  mysql:
    container_name: dev_site_mysql
    image: mysql:8.0.40
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - dev_site_network

networks:
  dev_site_network:
    name: dev_site_network
    driver: bridge
