services:
  php:
    build:
      dockerfile: docker/PHP.production.dockerfile
      context: .
    volumes:
      - ./public:/app/public
    networks:
      - nginx_network

  node:
    build:
      dockerfile: docker/NodeClient.production.dockerfile
      context: .
    volumes:
      - ./public:/app/public
    networks:
      - nginx_network


networks:
  nginx_network:
    external: true
