version: '3.5'
services:
  dev-site:
    container_name: dev-site
    image: ghcr.io/codelit/dev-site
    restart: always
    tty: true
    build:
      dockerfile: docker/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      # Important data files
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
      # Shared files after the container started
      - ./node_modules:/shared/node_modules
      - ./vendor:/shared/vendor
      - ./public:/shared/public

volumes:
  dev-site:
    name: dev-site

