version: '3'
services:
  mix:
    platform: linux/x86_64
    build:
      dockerfile: ./docker/mix/Dockerfile
    volumes:
      - .:/mix
    #    ports:
    #      - '35729:35729' # Livereload
    env_file:
      - .env
  composer:
    image: composer/composer
    tty: true
    volumes:
      - $PWD:/app
    working_dir: /app
    command: install
