version: '3.5'
services:
  dev-site:
    container_name: dev-site
    restart: always
    tty: true
    build:
      dockerfile: docker/Dockerfile
      context: .
    user: 1000:1000 # Fix for GitHub auto-rsync builds and removing old files
    env_file:
      - .env
    volumes:
      # Important data files
      - .env:/app/.env
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
      # Shared files after the container started
      - ./node_modules:/shared/node_modules
      - ./vendor:/shared/vendor
      - ./public:/shared/public
