services:
  php:
    build:
      dockerfile: docker/PHP.production.dockerfile
      context: .

  node:
    build:
      dockerfile: docker/NodeClient.production.dockerfile
      context: .
    ports:
      - "13714:13714" # SSR
