services:
  php:
    image: ghcr.io/codelit/dev-site:php-latest
    build:
      dockerfile: docker/PHP.production.dockerfile
      context: .
    networks:
      - nginx_network

  node:
    image: ghcr.io/codelit/dev-site:node-latest
    build:
      dockerfile: docker/NodeClient.production.dockerfile
      context: .
    networks:
      - nginx_network


networks:
  nginx_network:
    external: true
