name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV_PROD }}" > .env
#      - name: Build image
#        run: docker compose build
      - name: Deployment
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          stack_file_name: docker-compose.yml
          args: up -d
