name: Host-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Rsync files to remote server
        env:
          SSH_USERNAME: ${{ vars.SSH_USERNAME }}
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_PROJECT_FOLDER: ${{ vars.SSH_PROJECT_FOLDER }}
        run: |
          rsync -avzr --delete \
            --exclude='.git' \
            --exclude='.env' \
            ./ $SSH_USERNAME@$SSH_HOST:$SSH_PROJECT_FOLDER
