name: Host-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if .env file exists
        run: if [ ! -f .env ]; then cp .env.example .env; fi
      - name: Docker-compose build
        run: docker-compose build
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to the container registry
        run: docker-compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rsync deploy
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
            --exclude=".env"
            --exclude=".git/"
            --exclude="node_modules/"
            --exclude="vendor/"
            --exclude="storage/app/*"
            --exclude="public/build/*"
            --exclude="public/img/*"
          path: ./
          remote_path: ${{ vars.SSH_PROJECT_FOLDER }}
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH run actions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.SSH_PROJECT_FOLDER }}
            make pull
            make prod
