name: Host-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rsync deploy
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
            --exclude=".git/"
            --exclude=".env"
            --exclude="vendor/"
            --exclude="node_modules/"
            --exclude="storage/"
          path: ./
          remote_path: ${{ vars.SSH_PROJECT_FOLDER }}
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH run actions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.SSH_PROJECT_FOLDER }}
            && bash shell/deploy.sh
