name: Host-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        run: |
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: APP_ENV=production task build

      - name: Push Docker image to registry
        run: task push

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rsync deploy
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -zhrv --delete
            --exclude=".git/"
            --exclude=".idea/"
            --exclude=".vscode/"
            --exclude=".github/"
            --exclude=".env"
            --exclude="data/"
            --exclude="storage/"
            --exclude="docs/"
            --exclude="public/build/"
            --exclude="bootstrap/cache/"
            --exclude="bootstrap/ssr/"
            --exclude="node_modules/"
            --exclude="vendor/"
          path: ./
          remote_path: ${{ vars.SSH_PROJECT_FOLDER }}
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy files with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker/php_settings.ini"
          target: ${{ vars.SSH_PROJECT_FOLDER }}

      - name: SSH to deploy on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ vars.SSH_PROJECT_FOLDER }}
            APP_ENV=production task pull
            APP_ENV=production task prod
            docker system prune -af --volumes
